### ISSUE TITLE
Pandas==2.0.0 requirement

### ISSUE THREAD

**Issue by Tonylac77** [cch1999/posecheck#13]
Hi and firstly thanks for the great work done here.

I was wondering if the pandas version 2.0.0 is a hard requirement, seems quite odd to me that it would be. I am trying to get a conda-forge recipe for this going, and this is predictably causing dependency issues.

If needed I can create a PR to change the ==2.0.0 to >=2.0.0

Cheers

**Comment by cch1999** [comment]
Thanks @Tonylac77 !

Fixed in #14
